import grpc
import numpy as np
import torch
from torch.utils.data import IterableDataset

# These would be generated by grpc_tools.protoc
try:
    from . import permstream_pb2 as pb2
    from . import permstream_pb2_grpc as pb2_grpc
except ImportError:
    # If not generated, we can't run but we can show the implementation
    pb2 = None
    pb2_grpc = None

class PermStreamDataset(IterableDataset):
    def __init__(self, container_path, file_paths, endpoint="localhost:50051"):
        self.container_path = container_path
        self.file_paths = file_paths
        self.endpoint = endpoint

    def __iter__(self):
        if pb2_grpc is None:
            raise ImportError("Please generate gRPC code using protoc")
            
        # Increase message size limits to 64MB
        MAX_MESSAGE_LENGTH = 64 * 1024 * 1024
        options = [
            ('grpc.max_send_message_length', MAX_MESSAGE_LENGTH),
            ('grpc.max_receive_message_length', MAX_MESSAGE_LENGTH),
        ]
        channel = grpc.insecure_channel(self.endpoint, options=options)
        stub = pb2_grpc.PermStreamDataNodeStub(channel)
        
        request = pb2.TensorRequest(
            container_path=self.container_path,
            file_paths=self.file_paths
        )
        
        for response in stub.StreamTensors(request):
            # Efficiently convert bytes to numpy/torch without extra copies if possible
            # Here we assume response.dtype and response.shape are provided
            data = np.frombuffer(response.tensor_data, dtype=response.dtype)
            data = data.reshape(response.shape)
            yield torch.from_numpy(data.copy()) # .copy() to own memory if needed

def get_dataloader(container_path, file_paths, batch_size=32, endpoint="localhost:50051"):
    dataset = PermStreamDataset(container_path, file_paths, endpoint)
    return torch.utils.data.DataLoader(dataset, batch_size=batch_size)
