# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import permstream_pb2 as permstream__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in permstream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PermStreamDataNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChunk = channel.unary_unary(
                '/permstream.PermStreamDataNode/GetChunk',
                request_serializer=permstream__pb2.ChunkRequest.SerializeToString,
                response_deserializer=permstream__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.StreamTensors = channel.unary_stream(
                '/permstream.PermStreamDataNode/StreamTensors',
                request_serializer=permstream__pb2.TensorRequest.SerializeToString,
                response_deserializer=permstream__pb2.TensorResponse.FromString,
                _registered_method=True)


class PermStreamDataNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermStreamDataNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChunk,
                    request_deserializer=permstream__pb2.ChunkRequest.FromString,
                    response_serializer=permstream__pb2.ChunkResponse.SerializeToString,
            ),
            'StreamTensors': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTensors,
                    request_deserializer=permstream__pb2.TensorRequest.FromString,
                    response_serializer=permstream__pb2.TensorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'permstream.PermStreamDataNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('permstream.PermStreamDataNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PermStreamDataNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permstream.PermStreamDataNode/GetChunk',
            permstream__pb2.ChunkRequest.SerializeToString,
            permstream__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/permstream.PermStreamDataNode/StreamTensors',
            permstream__pb2.TensorRequest.SerializeToString,
            permstream__pb2.TensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
