# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: permstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'permstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10permstream.proto\x12\npermstream\"L\n\x0c\x43hunkRequest\x12\x16\n\x0e\x63ontainer_path\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\r\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\r\"\x1d\n\rChunkResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\";\n\rTensorRequest\x12\x16\n\x0e\x63ontainer_path\x18\x01 \x01(\t\x12\x12\n\nfile_paths\x18\x02 \x03(\t\"n\n\x0eTensorResponse\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x15\n\ris_last_chunk\x18\x04 \x01(\x08\x12\x12\n\nfile_index\x18\x05 \x01(\r2\x9f\x01\n\x12PermStreamDataNode\x12?\n\x08GetChunk\x12\x18.permstream.ChunkRequest\x1a\x19.permstream.ChunkResponse\x12H\n\rStreamTensors\x12\x19.permstream.TensorRequest\x1a\x1a.permstream.TensorResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'permstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKREQUEST']._serialized_start=32
  _globals['_CHUNKREQUEST']._serialized_end=108
  _globals['_CHUNKRESPONSE']._serialized_start=110
  _globals['_CHUNKRESPONSE']._serialized_end=139
  _globals['_TENSORREQUEST']._serialized_start=141
  _globals['_TENSORREQUEST']._serialized_end=200
  _globals['_TENSORRESPONSE']._serialized_start=202
  _globals['_TENSORRESPONSE']._serialized_end=312
  _globals['_PERMSTREAMDATANODE']._serialized_start=315
  _globals['_PERMSTREAMDATANODE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
